---
- name: Simulacao de Configuracao do Servidor (Modo de Seguranca)
  hosts: localhost
  tasks:
    - name: Validando ambiente de deploy
      debug:
        msg: "Iniciando configuracao do servidor virtual..."

    - name: Simulando instalacao do Docker e dependencias
      debug:
        msg: "Docker, Git e dependencias instalados com sucesso no host."

    - name: Simulando deploy dos microsservicos
      debug:
        msg: "Microsservico de Livros (8001) e Emprestimos (8002) configurados!"
